language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
after_success:
  - npm run codecov
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
