// flow-typed signature: 862d75f00e60ae9e50fb51a38f8ee81d
// flow-typed version: <<STUB>>/lodash.padend_v^4.6.1/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.padend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.padend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.padend/index' {
  declare module.exports: $Exports<'lodash.padend'>;
}
declare module 'lodash.padend/index.js' {
  declare module.exports: $Exports<'lodash.padend'>;
}
